### ISSUE TITLE
grant stella-emu team write access

### ISSUE THREAD

**Issue by SvOlli** [flathub/io.github.stella_emu.Stella#1]
Hello @barthalion and @hfiguiere !

I'm asking you, because you guided me getting this into flathub: could you please grant the team @stella-emu the same rights that I have? I still want to do "all the work" concerning flathub, but I also want to make sure that they are not "locked out".

Thanks in advance,
SvOlli

**Comment by barthalion** [comment]
There's no way to somehow "link" organization to a repo in another organization. I have manually invited members of @stella-emu to the repo.
